server:
  port: 8761  # Eureka Server runs on port 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false  # Eureka Server does not register itself
    fetch-registry: false
